In [1]:
import torch
import torch.nn as nn
torch.manual_seed(42)

# Deconvolution - Transpose Convolution

In [2]:
TransposeConv = nn.ConvTranspose2d(
    in_channels = 1,
    out_channels = 1,
    kernel_size = 2,
    bias = False,
)

In [3]:
TransposeConv.weight.data = torch.ones(
    TransposeConv.weight.data.shape
)

In [4]:
TransposeConv.weight

Parameter containing:
tensor([[[[1., 1.],
          [1., 1.]]]], requires_grad=True)

In [5]:
input = torch.randint(
    5, (1,2,2), dtype = torch.float32
)
input

tensor([[[1., 0.],
         [0., 4.]]])

In [6]:
ouput = TransposeConv(input)
ouput

tensor([[[1., 1., 0.],
         [1., 5., 4.],
         [0., 4., 4.]]], grad_fn=<SqueezeBackward1>)

# Padding in Transpose Convolution

In [7]:
TransposeConv = nn.ConvTranspose2d(
    in_channels = 1,
    out_channels = 1,
    kernel_size = 2,
    bias = False,
    padding = 1
)

In [8]:
TransposeConv.weight.data = torch.ones(
    TransposeConv.weight.data.shape
)

In [9]:
output = TransposeConv(input)
output

tensor([[[5.]]], grad_fn=<SqueezeBackward1>)

# Stride in Transpose Convolution

In [10]:
TransposeConv = nn.ConvTranspose2d(
    in_channels = 1,
    out_channels = 1,
    kernel_size = 2,
    bias = False,
    stride = 2,
)

In [11]:
TransposeConv.weight.data = torch.ones(
    TransposeConv.weight.data.shape
)

In [12]:
ouput = TransposeConv(input)
ouput

tensor([[[1., 1., 0., 0.],
         [1., 1., 0., 0.],
         [0., 0., 4., 4.],
         [0., 0., 4., 4.]]], grad_fn=<SqueezeBackward1>)

# Multi channels in Transpose Convolution

In [13]:
Input = torch.randint(
    5, (2,2,2), dtype = torch.float32
)
Input

tensor([[[0., 0.],
         [2., 1.]],

        [[4., 1.],
         [3., 1.]]])

In [14]:
TransposeConv = nn.ConvTranspose2d(
    in_channels = 2,
    out_channels = 2,
    kernel_size = 2,
    bias = False,
    stride = 2,
)

In [15]:
TransposeConv.weight.data = torch.ones(
    TransposeConv.weight.data.shape
)

In [16]:
TransposeConv.weight

Parameter containing:
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]], requires_grad=True)

In [17]:
output = TransposeConv(Input)
output

tensor([[[4., 4., 1., 1.],
         [4., 4., 1., 1.],
         [5., 5., 2., 2.],
         [5., 5., 2., 2.]],

        [[4., 4., 1., 1.],
         [4., 4., 1., 1.],
         [5., 5., 2., 2.],
         [5., 5., 2., 2.]]], grad_fn=<SqueezeBackward1>)